// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_todo_practice

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type Todo struct {
	ID     int    `json:"id"`
	UserID int    `json:"user_id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	User   *User  `json:"user"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
